language: go
services:
- docker
sudo: required
go:
- go1.9.3
script:
- make test
before_deploy:
- make debs
- export DEB_VERSION=$(git describe --tags --always | sed s/^v//)
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- make docker-push
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: X0L3J3k9YGaIUESz22nkTf92d74LXSSOx3LiX/rLlUjavYLX06qlzRGr0nDrrBvYOM3QgkRQWgeaQUgCoPsBP2sFOya47jDl6cg7mKgw4GUPj5fwi82JeOxKOvoLhcXqttgJAaX74J61idvldjyzRtQiTftqj0HpGJj8uW4qb4I=
  file: log-shuttle_${DEB_VERSION}_amd64.deb
  on:
    tags: true
    repo: heroku/log-shuttle
env:
  global:
  - secure: PGlgN8iLUyf0+JgPS774jVms0RxlLvyF9mH0mofca/kGb2tgCrSkbZMFMPhBmcPISNP/RPKugrO6rrAGMvm+C04VC+NCfr32im5Al4Of0inhlwi6Xk015LfDYs6Oo8GHRMa4XSCnfhkIx+/xUO1w9JeE5vtVGEPTGcLnNbRZQ84=
  - secure: I6Yk2OKzgelw1mkwZyq5kUxt8UOfFM3TEf9Wa4NpInshmbP8fxUZEeD+gMAQOneuICiM0RwfOomikqGeEcYiery2/WDILZ5j4+0MqyKthoBqTDRHhVw/r9Y7hQ3gGiSq1s2CihiEL++Jkatxm9PaxxOxaYiFDvtk8ALCC4rc1AA=
  - secure: dTATw5SQCuegg8ZDvlOe+P0op4aE++CGKujKBJhCbbsvf6nU5m1ykb5DIM4Gbb+qD76rTaqafU2l75ag8hhBIeGDTgwSmNHgGbJU/HapI65UVaupmH5SY7kMnIsL5jbiAlLPWPaMABQFN588UVxcWF71CekD0zGVd6i5fAGYjA0=
