language: go
go:
- 1.4.1
before_install:
- go get github.com/tools/godep
- export PATH=${HOME}/gopath/bin:$PATH
- export LVER=$(git describe --tags --always | sed s/^v//)
- echo $GOPATH
script:
- godep go test -v ./...
before_deploy:
- godep go install -a -ldflags "-X main.version ${LVER}" ./...
- export tmp=./tmp
- export deb_root=${tmp}/build
- export debout=${tmp}/deb
- mkdir -p ${deb_root}/DEBIAN
- mkdir -p ${debout}
- export controlfile=./tmp/build/DEBIAN/control
- export installpath=${deb_root}/usr/bin
- "sed s/{{LVER}}/${LVER}/ < misc/DEBIAN.control > ${controlfile}"
- cat ${controlfile}
- mkdir -p ${installpath}
- install $HOME/gopath/bin/log-shuttle ${installpath}/log-shuttle
- fakeroot dpkg-deb --build ${deb_root} ${debout}
notifications:
  hipchat:
    rooms:
      secure: JaAp09GeSWHDYVzUFcW/9f2bXt/IlC85cNbByvgv1BNR6fVhem2p7MANeY6fpcWw9R9GajZSi/XBNKUbRRdMIroifOEJxa8ewp0Un2a79Lj0kmINZz8isgtP6cIY3tkozXQqQVFRE1lokAGU4wxh7/hjTMf1A7AOTpwKLKatw4w=
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: X0L3J3k9YGaIUESz22nkTf92d74LXSSOx3LiX/rLlUjavYLX06qlzRGr0nDrrBvYOM3QgkRQWgeaQUgCoPsBP2sFOya47jDl6cg7mKgw4GUPj5fwi82JeOxKOvoLhcXqttgJAaX74J61idvldjyzRtQiTftqj0HpGJj8uW4qb4I=
  file:
    - ${debout}/log-shuttle_${LVER}_amd64.deb
    - ${HOME}/gopath/bin/log-shuttle
  on:
    all_branches: true
    tags: true
    repo: heroku/log-shuttle
