language: go
sudo: false
go:
- 1.6
script:
- make test
before_deploy:
- make debs
- export DEB_VERSION=$(git describe --tags --always | sed s/^v//)
notifications:
  hipchat:
    rooms:
    - secure: "QUMhx7wwa/+gRlSLhXbANh2BoNpPR8TkxwCaRSK8/hAx2UAYExcPzkkobZrhkPCWFT6Cmbtem6j/o2/5DiR8cBb+2QSeBHWBS8Rm+zLfmlWTGOywm8mjQW+kgaUveQSBz7quV+X2Qv0yO7QORH2sWobU1NP3OTu26PfOBaNxYLA="
    template:
    - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}
      (<a href="%{build_url}">Details</a> | <a href="%{compare_url}">Change view</a>)'
    format: html
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: X0L3J3k9YGaIUESz22nkTf92d74LXSSOx3LiX/rLlUjavYLX06qlzRGr0nDrrBvYOM3QgkRQWgeaQUgCoPsBP2sFOya47jDl6cg7mKgw4GUPj5fwi82JeOxKOvoLhcXqttgJAaX74J61idvldjyzRtQiTftqj0HpGJj8uW4qb4I=
  file: log-shuttle_${DEB_VERSION}_amd64.deb
  on:
    all_branches: true
    tags: true
    repo: heroku/log-shuttle
